Update action.yml

diff --git a/.github/actions/action.yml b/.github/actions/action.yml
--- a/.github/actions/action.yml
+++ b/.github/actions/action.yml
@@ -35,24 +35,32 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Maximize Build Space
-      uses: AdityaGarg8/remove-unwanted-software@v5
-      with:
-        remove-dotnet: 'true' # Frees ~2 GB
-        remove-android: 'true' # Frees ~9 GB
-        remove-haskell: 'true' # Frees ~5.2 GB
-        remove-codeql: 'true' # Frees ~5.4 GB
-        remove-docker-images: 'true' # Frees ~3.2 GB
-        remove-large-packages: 'true' # Frees ~3.1 GB
-        remove-swapfile: 'true' # Frees ~4 GB
-        remove-cached-tools: 'false' # Avoid unless confirmed safe
-        verbose: 'true' # Enable detailed logging
-
     - name: Setup Build System
       shell: bash
       run: |
         export DEBIAN_FRONTEND=noninteractive
         echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
+        df -h
+        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
+        sudo docker image prune --all --force
+        echo "some directories deleted"
+        # Remove large unwanted packages
+        sudo apt-get purge -y \
+          aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+          esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+          google-cloud-sdk imagemagick \
+          libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+          mercurial apt-transport-https mono-complete libmysqlclient \
+          unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+          libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+          snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+          sphinxsearch subversion mongodb-org microsoft-edge-stable || true
+        # Regex-based purges (for bulk families like mysql, php, dotnet)
+        sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
+        # Clean up
+        sudo apt-get autoremove -y
+        sudo apt-get autoclean -y
+        echo "some packages purged"
         df -h
         # Install dependencies
         echo "Installing Repo, Python, and build tools"
